app/posts/forms.py
import wtforms
from wtforms.validators import DataRequired

from models import Post

from models import Tag
class TagField(wtforms.StringField):
    def _value(self):
        if self.data:
            # Display tags as a comma-separated list.
            return ', '.join([tag.name for tag in self.data])
        return ''

    def get_tags_from_string(self, tag_string):
        raw_tags = tag_string.split(',')
        # Filter out any empty tag names.
        tag_names = [name.strip() for name in raw_tags if name.strip()]
        # Query the database and retrieve any tags we have already saved.
        existing_tags = Tag.query.filter(Tag.name.in_(tag_names))
        # Determine which tag names are new.
        new_names = set(tag_names) - set([tag.name for tag in existing_tags])
        # Create a list of unsaved Tag instances for the new tags.
        new_tags = [Tag(name=name) for name in new_names]
        # Return all the existing tags + all the new, unsaved tags.
        return list(existing_tags) + new_tags

    def process_formdata(self, valuelist):
        if valuelist:
            self.data = self.get_tags_from_string(valuelist[0])
        else:
            self.data = []


class PostForm(wtforms.Form):
    title = wtforms.StringField(
        'Title',
        validators=[DataRequired()])
    body = wtforms.TextAreaField(
        'Body',
        validators=[DataRequired()])
    status = wtforms.SelectField(
        'Post status',
        choices=(
            (Post.STATUS_PUBLIC, 'Public'),
            (Post.STATUS_DRAFT, 'Draft')),
        coerce=int)
    tags = TagField(
        'Tags',
        description='Separate multiple tags with commas.')

    def save_post(self, post):
        self.populate_obj(post)
        post.generate_slug()
        return post


class ImageForm(wtforms.Form):
    file = wtforms.FileField('Image file')

app/posts/blueprint.py
import os

from flask import Blueprint, flash, redirect, render_template, request, url_for, g
from werkzeug import secure_filename
#??from app import db
from flask_login import login_required #decorator

from app import app, db
from helpers import object_list
from models import Post, Tag
from posts.forms import PostForm, ImageForm

posts = Blueprint('posts', __name__,template_folder='templates')

def post_list(template, query, **context):
    query = filter_status_by_user(query)

    valid_statuses = (Post.STATUS_PUBLIC, Post.STATUS_DRAFT)
    query = query.filter(Post.status.in_(valid_statuses))
    if request.args.get('q'):
        search = request.args['q']
        query = query.filter(
            (Post.body.contains(search)) |
            (Post.title.contains(search)))
    return object_list(template, query, **context)


def get_post_or_404(slug, author=None):
    query = Post.query.filter(Post.slug == slug)
    if author:
        query = query.filter(Post.author == author)
    else:
        query = filter_status_by_user(query)
    return query.first_or_404()


def filter_status_by_user(query):
    if not g.user.is_authenticated:
        return query.filter(Post.status == Post.STATUS_PUBLIC)
    else:
        # Allow user to view their own drafts.
        query = query.filter(
            (Post.status == Post.STATUS_PUBLIC) |
            ((Post.author == g.user) & (Post.status != Post.STATUS_DELETED)))
    return query



@posts.route('/')
def index():
    posts = Post.query.order_by(Post.created_timestamp.desc())
    return post_list('posts/index.html', posts)

@posts.route('/tags/')
def tag_index():
    tags = Tag.query.order_by(Tag.name)
    return object_list('posts/tag_index.html', tags)

@posts.route('/tags/<slug>/')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.order_by(Post.created_timestamp.desc())
    return object_list('posts/tag_detail.html', posts, tag=tag)


# CREATE POST
#from app import db
@posts.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'POST':
        form = PostForm(request.form)
        if form.validate():
            post = form.save_post(Post(author=g.user))
            db.session.add(post)
            db.session.commit()
            flash('Post "%s" created successfully.' % post.title, 'success')
            return redirect(url_for('posts.detail', slug=post.slug))
    else:
        form = PostForm()
    return render_template('posts/create.html', form=form)


# DETAIL VIEW / display post
@posts.route('/<slug>/')
def detail(slug):
    post = get_post_or_404(slug)
    return render_template('posts/detail.html', post=post)


# EDIT POST
@posts.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit(slug):
    post = get_post_or_404(slug, author=None)
    #post = Post.query.filter(Post.slug == slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(request.form, obj=post)
        if form.validate():
            post = form.save_post(post)
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('posts.detail', slug=post.slug))
    else:
        form = PostForm(obj=post)
    return render_template('posts/edit.html', post=post, form=form)

# DELETE POST
@posts.route('/<slug>/delete/', methods=['GET', 'POST'])
@login_required
def delete(slug):
    post = get_post_or_404(slug, author=None)
    if request.method == 'POST':
        post.status = Post.STATUS_DELETED
        db.session.add(post)
        db.session.commit()
        flash('Post "%s" has been deleted.' % post.title, 'success')
        return redirect(url_for('posts.index'))
    return render_template('posts/delete.html', post=post)

# IMAGES
@posts.route('/image-upload/', methods=['GET', 'POST'])
@login_required
def image_upload():
    if request.method == 'POST':
        form = ImageForm(request.form)
        if form.validate():
            image_file = request.files['file']
            filename = os.path.join(app.config['IMAGES_DIR'], secure_filename(image_file.filename))
            image_file.save(filename)
            flash('Saved %s' % os.path.basename(filename), 'success')
            return redirect(url_for('posts.index'))
    else:
        form = ImageForm()
    return render_template('posts/image_upload.html', form=form)

app/posts/templates/posts/base_posts.html
{% extends "base.html" %}
{% block sidebar %}
    <form class="form-inline well" method="get" role="form">
        <div class="input-group">
            <input class="form-control input-xs" name="q" placeholder="Search..." value="{{ request.args.get('q', '') }}" />
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go</button>
            </span>
        </div>
    </form>
{% endblock %}
{% block content %}
    {% include "inc/list.html" %}
    {% include "inc/page_links.html" %}
{% endblock %}

app/posts/templates/posts/create.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}

{% block title %}Create new post{% endblock %}

{% block content_title %}Create new post{% endblock %}

{% block content %}
    <form action="{{ url_for('posts.create') }}" class="form formhorizontal" method="post">
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btndefault">Create</button>
                <a class="btn" href="{{ url_for('posts.index') }}">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}

app/posts/templates/posts/delete.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content_title %}{{ post.title }}{% endblock %}

{% block content %}
    <form action="{{ url_for('posts.delete', slug=post.slug) }}" method="post">
        <fieldset>
            <legend>Delete this post?</legend>
            <button class="btn btn-danger" type="submit">Delete</button>
            <a class="btn" href="{{ url_for('posts.detail', slug=post.slug) }}">Cancel</a>
        </fieldset>
    </form>
{% endblock %}

app/posts/templates/posts/detail.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content_title %}{{ post.title }}{% endblock %}
{% block sidebar %}
    <ul class="well nav nav-list">
        <li><h4>Tags</h4></li>
        {% for tag in post.tags %}
            <li><a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></li>
        {% endfor %}
        {% if g.user == post.author %}
            <li><h4>Actions</h4></li>
            <li><a href="{{ url_for('posts.edit', slug=post.slug) }}">Edit</a></li>
            <li><a href="{{ url_for('posts.delete', slug=post.slug) }}">Delete</a></li>
            <li><a href="{{ url_for('posts.create', slug=post.slug) }}">Create new</a></li>
        {% endif %}
    </ul>

<p>Published {{ post.created_timestamp.strftime('%m/%d/%Y') }}</p>
<p>Author {{ post.author.name }}</p>
{% endblock %}
{% block content %}
{{ post.body }}
{% endblock %}

app/posts/templates/posts/edit.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}

{% block title %}Edit {{ post.title }}{% endblock %}

{% block content_title %}Edit {{ post.title }}{% endblock %}

{% block content %}
    <form action="{{ url_for('posts.edit', slug=post.slug) }}" class="form form-horizontal" method="post">
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Save</button>
                <a class="btn" href="{{ url_for('posts.detail', slug=post.slug) }}">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}

app/posts/templates/posts/image_upload.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}

{% block title %}Upload an image{% endblock %}

{% block content_title %}Upload an image{% endblock %}
{% block content %}
    <form action="{{ url_for('posts.image_upload') }}" enctype="multipart/form-data" method="post">
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btndefault">Upload</button>
                <a class="btn" href="{{ url_for('posts.index') }}">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}

app/posts/templates/posts/index.html
{% extends "posts/base_posts.html" %}
{% block title %}Posts{% endblock %}
{% block content_title %}Posts{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends "posts/base_posts.html" %}
{% block title %}Tags{% endblock %}
{% block content_title %}Tags{% endblock %}

app/posts/templates/posts/tag_index.html
{% extends "base.html" %}
{% block title %}Tags{% endblock %}
{% block content_title %}Tags{% endblock %}
{% block content %}
    <ul>
        {% for tag in object_list.items %}
        <li><a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}